import type { ApplicationDraft } from '@onfile/core';

export const MOCK_APPLICATIONS: ApplicationDraft[] = [
  {
    id: 'app-001',
    jobId: 'job-001',
    jobTitle: 'Backend Engineer — Payments Infrastructure',
    company: 'Stripe',
    resumeVersionId: 'rv-002',
    status: 'interview',
    matchScore: 87,
    coverLetter: 'Dear Stripe team, I am excited to apply for the Backend Engineer role on the Payments Infrastructure team...',
    formStructure: [
      { type: 'text', label: 'Full Name', required: true, value: 'Alex Chen' },
      { type: 'text', label: 'Email', required: true, value: 'alex.chen@university.edu' },
      { type: 'file', label: 'Resume', required: true },
      { type: 'textarea', label: 'Why do you want to work at Stripe?', required: true },
      { type: 'dropdown', label: 'Years of Python experience', required: true, options: ['0-1', '1-2', '2-3', '3+'], value: '2-3' },
    ],
    answers: {
      'Why do you want to work at Stripe?': 'I interned at Stripe last summer and was deeply impressed by the engineering culture and the scale of problems the payments infrastructure team solves...',
    },
    missingSkills: ['Distributed Systems', 'Go'],
    createdAt: '2026-02-16T15:00:00Z',
    approvedAt: '2026-02-17T10:00:00Z',
    submittedAt: '2026-02-17T10:05:00Z',
  },
  {
    id: 'app-002',
    jobId: 'job-004',
    jobTitle: 'Full Stack Engineer — Growth',
    company: 'Linear',
    resumeVersionId: 'rv-003',
    status: 'submitted',
    matchScore: 84,
    coverLetter: 'To the Linear team, I have been a daily Linear user for over a year and would love to contribute...',
    formStructure: [
      { type: 'text', label: 'Full Name', required: true, value: 'Alex Chen' },
      { type: 'text', label: 'Email', required: true, value: 'alex.chen@university.edu' },
      { type: 'file', label: 'Resume', required: true },
      { type: 'textarea', label: 'What excites you most about Linear?', required: true },
    ],
    answers: {
      'What excites you most about Linear?': "Linear's obsession with developer experience and speed mirrors how I approach building software...",
    },
    missingSkills: ['GraphQL'],
    createdAt: '2026-02-18T12:00:00Z',
    approvedAt: '2026-02-19T09:00:00Z',
    submittedAt: '2026-02-19T09:10:00Z',
  },
  {
    id: 'app-003',
    jobId: 'job-007',
    jobTitle: 'Backend Engineer — Data Platform',
    company: 'Retool',
    resumeVersionId: 'rv-004',
    status: 'approved',
    matchScore: 85,
    formStructure: [
      { type: 'text', label: 'Full Name', required: true, value: 'Alex Chen' },
      { type: 'text', label: 'Email', required: true, value: 'alex.chen@university.edu' },
      { type: 'file', label: 'Resume', required: true },
      { type: 'textarea', label: 'Describe a complex API you built', required: true },
    ],
    answers: {
      'Describe a complex API you built': 'At Stripe, I designed and built a REST API for reconciliation data with three endpoints...',
    },
    missingSkills: ['GraphQL', 'Redis'],
    createdAt: '2026-02-19T14:00:00Z',
    approvedAt: '2026-02-20T08:00:00Z',
  },
  {
    id: 'app-004',
    jobId: 'job-002',
    jobTitle: 'Software Engineer — Developer Platform',
    company: 'Vercel',
    resumeVersionId: 'rv-001',
    status: 'drafted',
    matchScore: 82,
    formStructure: [
      { type: 'text', label: 'Full Name', required: true, value: 'Alex Chen' },
      { type: 'text', label: 'Email', required: true, value: 'alex.chen@university.edu' },
      { type: 'file', label: 'Resume', required: true },
      { type: 'textarea', label: 'What would you improve in the Vercel CLI?', required: false },
    ],
    answers: {},
    missingSkills: ['CLI Development'],
    createdAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'app-005',
    jobId: 'job-006',
    jobTitle: 'Software Engineering Intern — Infrastructure',
    company: 'Notion',
    resumeVersionId: 'rv-001',
    status: 'drafted',
    matchScore: 79,
    formStructure: [
      { type: 'text', label: 'Full Name', required: true, value: 'Alex Chen' },
      { type: 'text', label: 'Email', required: true, value: 'alex.chen@university.edu' },
      { type: 'file', label: 'Resume', required: true },
    ],
    answers: {},
    missingSkills: ['Redis', 'Kafka'],
    createdAt: '2026-02-20T11:00:00Z',
  },
  {
    id: 'app-006',
    jobId: 'job-008',
    jobTitle: 'Engineering Intern — API Platform',
    company: 'Plaid',
    resumeVersionId: 'rv-001',
    status: 'offer',
    matchScore: 76,
    formStructure: [],
    answers: {},
    missingSkills: ['AWS', 'Terraform'],
    createdAt: '2026-01-20T10:00:00Z',
    approvedAt: '2026-01-21T09:00:00Z',
    submittedAt: '2026-01-21T09:15:00Z',
    responseTimeDays: 12,
  },
];
