import type { InterviewKit } from '@onfile/core';

export const MOCK_INTERVIEW_KITS: InterviewKit[] = [
  {
    id: 'kit-001',
    applicationId: 'app-001',
    jobTitle: 'Backend Engineer — Payments Infrastructure',
    company: 'Stripe',
    interviewType: 'mixed',
    questions: [
      {
        id: 'q-001',
        text: 'Design a rate limiting system for a payments API that handles 100k requests per second.',
        category: 'technical',
        difficulty: 'hard',
        contextNotes: 'Stripe processes high transaction volumes. Focus on correctness and failure modes.',
        skills: ['Distributed Systems', 'REST APIs', 'System Design'],
      },
      {
        id: 'q-002',
        text: 'Given a PostgreSQL table with 50M rows of transaction records, how would you optimize a query that fetches all failed transactions in the last 30 days?',
        category: 'technical',
        difficulty: 'medium',
        contextNotes: 'PostgreSQL indexing, EXPLAIN ANALYZE, partial indexes.',
        skills: ['PostgreSQL', 'SQL', 'Performance'],
      },
      {
        id: 'q-003',
        text: 'Walk me through how you would design a webhook delivery system that guarantees at-least-once delivery.',
        category: 'technical',
        difficulty: 'hard',
        contextNotes: 'Stripe is known for its webhook system. Discuss idempotency, retries, dead letter queues.',
        skills: ['Distributed Systems', 'REST APIs', 'Backend'],
      },
      {
        id: 'q-004',
        text: 'Tell me about a time you had to debug a production issue under pressure. What was your process?',
        category: 'behavioral',
        difficulty: 'medium',
        contextNotes: 'Reference your on-call experience at Stripe internship.',
        skills: [],
      },
      {
        id: 'q-005',
        text: 'Describe a project where you had to make a significant technical trade-off. What did you choose and why?',
        category: 'behavioral',
        difficulty: 'medium',
        contextNotes: 'Use PriceWatch API or StudySync. Focus on the decision-making process.',
        skills: [],
      },
      {
        id: 'q-006',
        text: 'Why Stripe? What specifically about the Payments Infrastructure team interests you?',
        category: 'company_specific',
        difficulty: 'easy',
        contextNotes: 'You interned here — use specific observations from that experience.',
        skills: [],
      },
      {
        id: 'q-007',
        text: 'How do you ensure data consistency in a distributed system when a payment confirmation needs to update multiple services simultaneously?',
        category: 'technical',
        difficulty: 'hard',
        contextNotes: 'Two-phase commit, saga pattern, eventual consistency trade-offs.',
        skills: ['Distributed Systems', 'PostgreSQL'],
      },
    ],
    answerDrafts: [
      {
        questionId: 'q-004',
        situation: 'During my Stripe internship, we had a production incident where reconciliation data was showing incorrect totals for a subset of merchant accounts.',
        task: 'I was on-call rotation with a senior engineer and needed to help triage the issue within our SLA window.',
        action: 'I used our internal logging dashboard to trace the anomaly back to a recent migration script that had an off-by-one error in batch processing. I isolated the affected merchant IDs and drafted a hotfix.',
        result: 'The hotfix was reviewed and deployed within 2 hours. I wrote a post-mortem documenting the root cause and proposing an additional validation step in our migration pipeline.',
        reflection: 'I learned the importance of targeted logging and having clear runbooks. The incident response process at Stripe was well-defined and that structure helped me stay calm.',
      },
      {
        questionId: 'q-006',
        situation: 'I interned at Stripe last summer on the Payments Infrastructure team.',
        task: "I want to return full-time to the same team and continue the work I started on reconciliation tooling.",
        action: "During my internship, I saw firsthand how much reliability and correctness matter when you're processing billions in transactions. The engineering culture of ownership and the depth of the technical problems were unlike anything I'd experienced.",
        result: 'I shipped 3 production endpoints and resolved 2 incidents. Those experiences confirmed this is the environment where I want to grow as an engineer.',
        reflection: "Stripe's bar for reliability and clarity in systems thinking directly aligns with how I want to develop as an engineer.",
      },
    ],
    mockScores: [
      {
        sessionId: 'session-001',
        questionId: 'q-004',
        structureScore: 4,
        relevanceScore: 5,
        technicalDepth: 3,
        specificity: 4,
        clarity: 4,
        finalScore: 78,
        suggestions: ['Add more technical detail about the specific fix applied', 'Quantify the impact more precisely'],
        createdAt: '2026-02-19T16:00:00Z',
      },
    ],
    createdAt: '2026-02-17T12:00:00Z',
  },
];
