import type { Job } from '@onfile/core';

export const MOCK_JOBS: Job[] = [
  {
    id: 'job-001',
    title: 'Backend Engineer — Payments Infrastructure',
    company: 'Stripe',
    location: 'San Francisco, CA',
    remote: true,
    description: `We are looking for a Backend Engineer to join our Payments Infrastructure team. You will work on the systems that process billions of dollars in transactions every year. You'll design and build APIs, improve reliability, and help scale our core payment flows.\n\nResponsibilities:\n- Design, build, and maintain highly available backend services\n- Work closely with product teams to ship new payment features\n- Participate in on-call rotations and incident response\n\nWe value ownership, clear thinking, and a bias for action.`,
    skills: [
      { name: 'Python', required: true, userHas: true },
      { name: 'REST APIs', required: true, userHas: true },
      { name: 'PostgreSQL', required: true, userHas: true },
      { name: 'Distributed Systems', required: true, userHas: false },
      { name: 'Go', required: false, userHas: false },
      { name: 'Docker', required: false, userHas: true },
    ],
    matchScore: { overall: 87, tier: 'high', skillMatch: 90, experienceAlignment: 85, roleAlignment: 92, gapPenalty: 5 },
    status: 'interested',
    source: 'stripe.com/jobs',
    sourceUrl: 'https://stripe.com/jobs/listing/backend-engineer-payments',
    postedDate: '2026-02-15',
    createdAt: '2026-02-16T09:00:00Z',
  },
  {
    id: 'job-002',
    title: 'Software Engineer — Developer Platform',
    company: 'Vercel',
    location: 'Remote',
    remote: true,
    description: `Join Vercel's Developer Platform team to build the tools that millions of developers use every day. You'll work on our CLI, SDK, and APIs that power deployments.\n\nResponsibilities:\n- Build and maintain developer-facing APIs and SDKs\n- Improve the DX of the Vercel CLI\n- Collaborate with open-source contributors`,
    skills: [
      { name: 'TypeScript', required: true, userHas: true },
      { name: 'Node.js', required: true, userHas: true },
      { name: 'REST APIs', required: true, userHas: true },
      { name: 'CLI Development', required: false, userHas: false },
      { name: 'React', required: false, userHas: true },
    ],
    matchScore: { overall: 82, tier: 'high', skillMatch: 88, experienceAlignment: 78, roleAlignment: 85, gapPenalty: 8 },
    status: 'draft',
    source: 'vercel.com/careers',
    sourceUrl: 'https://vercel.com/careers/software-engineer-developer-platform',
    postedDate: '2026-02-14',
    createdAt: '2026-02-15T11:00:00Z',
  },
  {
    id: 'job-003',
    title: 'Backend Engineer Intern — FinTech',
    company: 'Brex',
    location: 'San Francisco, CA',
    remote: false,
    description: `Brex is building the financial operating system for growing businesses. Join our engineering team as a Backend Engineer Intern and work on core financial infrastructure.\n\nYou will:\n- Build and extend REST APIs for our spending management platform\n- Work with Elixir and PostgreSQL in a distributed system\n- Ship features end-to-end with product and design`,
    skills: [
      { name: 'REST APIs', required: true, userHas: true },
      { name: 'PostgreSQL', required: true, userHas: true },
      { name: 'Elixir', required: true, userHas: false },
      { name: 'Python', required: false, userHas: true },
      { name: 'Distributed Systems', required: false, userHas: false },
    ],
    matchScore: { overall: 71, tier: 'medium', skillMatch: 72, experienceAlignment: 75, roleAlignment: 80, gapPenalty: 18 },
    status: 'new',
    source: 'brex.com/careers',
    sourceUrl: 'https://www.brex.com/careers/backend-engineer-intern',
    postedDate: '2026-02-12',
    createdAt: '2026-02-13T08:00:00Z',
  },
  {
    id: 'job-004',
    title: 'Full Stack Engineer — Growth',
    company: 'Linear',
    location: 'Remote',
    remote: true,
    description: `Linear is building the next-generation project management tool. We are looking for a Full Stack Engineer to join our Growth team and help us reach more developers.\n\nYou will build:\n- Onboarding flows and growth experiments\n- Integration pages and SEO infrastructure\n- Internal analytics dashboards`,
    skills: [
      { name: 'TypeScript', required: true, userHas: true },
      { name: 'React', required: true, userHas: true },
      { name: 'Node.js', required: true, userHas: true },
      { name: 'PostgreSQL', required: false, userHas: true },
      { name: 'GraphQL', required: false, userHas: false },
    ],
    matchScore: { overall: 84, tier: 'high', skillMatch: 85, experienceAlignment: 80, roleAlignment: 86, gapPenalty: 6 },
    status: 'new',
    source: 'linear.app/careers',
    sourceUrl: 'https://linear.app/careers/full-stack-engineer',
    postedDate: '2026-02-17',
    createdAt: '2026-02-18T10:00:00Z',
  },
  {
    id: 'job-005',
    title: 'Platform Engineering Intern',
    company: 'Figma',
    location: 'San Francisco, CA',
    remote: false,
    description: `Figma's Platform team builds internal developer tooling, CI/CD infrastructure, and observability systems. As a Platform Engineering Intern, you will improve developer productivity across the org.\n\nYou'll work on:\n- Build system improvements\n- Metrics and alerting infrastructure\n- Internal CLI tooling`,
    skills: [
      { name: 'Python', required: true, userHas: true },
      { name: 'Docker', required: true, userHas: true },
      { name: 'Kubernetes', required: false, userHas: false },
      { name: 'CI/CD', required: false, userHas: false },
      { name: 'Bash', required: false, userHas: false },
    ],
    matchScore: { overall: 66, tier: 'medium', skillMatch: 65, experienceAlignment: 70, roleAlignment: 60, gapPenalty: 20 },
    status: 'new',
    source: 'figma.com/careers',
    sourceUrl: 'https://www.figma.com/careers/platform-engineering-intern',
    postedDate: '2026-02-10',
    createdAt: '2026-02-11T14:00:00Z',
  },
  {
    id: 'job-006',
    title: 'Software Engineering Intern — Infrastructure',
    company: 'Notion',
    location: 'San Francisco, CA',
    remote: true,
    description: `Join Notion's Infrastructure team to help us build the systems that serve millions of users. This internship is focused on backend systems, database reliability, and performance optimization.\n\nYou'll work on:\n- Database query optimization\n- API latency improvements\n- Data reliability tooling`,
    skills: [
      { name: 'Python', required: true, userHas: true },
      { name: 'PostgreSQL', required: true, userHas: true },
      { name: 'REST APIs', required: false, userHas: true },
      { name: 'Redis', required: false, userHas: false },
      { name: 'Kafka', required: false, userHas: false },
    ],
    matchScore: { overall: 79, tier: 'medium', skillMatch: 82, experienceAlignment: 78, roleAlignment: 75, gapPenalty: 12 },
    status: 'applied',
    source: 'notion.com/careers',
    sourceUrl: 'https://www.notion.so/careers/software-engineering-intern-infrastructure',
    postedDate: '2026-02-08',
    createdAt: '2026-02-09T09:30:00Z',
  },
  {
    id: 'job-007',
    title: 'Backend Engineer — Data Platform',
    company: 'Retool',
    location: 'San Francisco, CA',
    remote: false,
    description: `Retool is the fastest way to build internal tools. Our Data Platform team is building the layer that lets teams connect any data source to any UI. We're looking for a backend engineer who cares deeply about developer experience and API design.\n\nYou'll work on:\n- Data connector framework\n- Query execution engine\n- API versioning and reliability`,
    skills: [
      { name: 'TypeScript', required: true, userHas: true },
      { name: 'Node.js', required: true, userHas: true },
      { name: 'PostgreSQL', required: true, userHas: true },
      { name: 'REST APIs', required: true, userHas: true },
      { name: 'GraphQL', required: false, userHas: false },
      { name: 'Redis', required: false, userHas: false },
    ],
    matchScore: { overall: 85, tier: 'high', skillMatch: 90, experienceAlignment: 82, roleAlignment: 85, gapPenalty: 8 },
    status: 'new',
    source: 'retool.com/careers',
    sourceUrl: 'https://retool.com/careers/backend-engineer-data-platform',
    postedDate: '2026-02-16',
    createdAt: '2026-02-17T08:00:00Z',
  },
  {
    id: 'job-008',
    title: 'Engineering Intern — API Platform',
    company: 'Plaid',
    location: 'New York, NY',
    remote: false,
    description: `Plaid connects millions of people to their financial accounts. Our API Platform team builds the core infrastructure that hundreds of thousands of developers use to access financial data.\n\nResponsibilities:\n- Build and maintain internal API tooling\n- Improve API documentation infrastructure\n- Work on rate limiting and quota management systems`,
    skills: [
      { name: 'Python', required: true, userHas: true },
      { name: 'REST APIs', required: true, userHas: true },
      { name: 'PostgreSQL', required: false, userHas: true },
      { name: 'AWS', required: false, userHas: false },
      { name: 'Terraform', required: false, userHas: false },
    ],
    matchScore: { overall: 76, tier: 'medium', skillMatch: 80, experienceAlignment: 75, roleAlignment: 78, gapPenalty: 14 },
    status: 'new',
    source: 'plaid.com/careers',
    sourceUrl: 'https://plaid.com/careers/openings/engineering/engineering-intern-api-platform',
    postedDate: '2026-02-13',
    createdAt: '2026-02-14T10:00:00Z',
  },
];
