import type { UserProfile } from '@onfile/core';

export const MOCK_PROFILE: UserProfile = {
  id: 'profile-001',
  name: 'Alex Chen',
  email: 'alex.chen@university.edu',
  phone: '+1 (555) 234-5678',
  location: 'San Francisco, CA',
  linkedIn: 'linkedin.com/in/alexchen-dev',
  github: 'github.com/alexchen-dev',
  portfolio: 'alexchen.dev',
  skills: [
    { id: 'sk-1', name: 'Python', level: 'advanced', confidenceScore: 88, yearsOfExperience: 3, tags: ['backend', 'scripting', 'ml'] },
    { id: 'sk-2', name: 'TypeScript', level: 'advanced', confidenceScore: 82, yearsOfExperience: 2, tags: ['frontend', 'backend'] },
    { id: 'sk-3', name: 'React', level: 'intermediate', confidenceScore: 74, yearsOfExperience: 2, tags: ['frontend'] },
    { id: 'sk-4', name: 'Node.js', level: 'intermediate', confidenceScore: 70, yearsOfExperience: 2, tags: ['backend'] },
    { id: 'sk-5', name: 'PostgreSQL', level: 'intermediate', confidenceScore: 65, yearsOfExperience: 1.5, tags: ['database'] },
    { id: 'sk-6', name: 'FastAPI', level: 'intermediate', confidenceScore: 72, yearsOfExperience: 1, tags: ['backend', 'python'] },
    { id: 'sk-7', name: 'REST APIs', level: 'advanced', confidenceScore: 85, yearsOfExperience: 2.5, tags: ['backend', 'integration'] },
    { id: 'sk-8', name: 'Git', level: 'advanced', confidenceScore: 90, yearsOfExperience: 3, tags: ['tooling'] },
    { id: 'sk-9', name: 'Docker', level: 'beginner', confidenceScore: 40, yearsOfExperience: 0.5, tags: ['devops'] },
    { id: 'sk-10', name: 'SQL', level: 'intermediate', confidenceScore: 68, yearsOfExperience: 2, tags: ['database'] },
  ],
  projects: [
    {
      id: 'proj-1',
      name: 'StudySync',
      description: 'A collaborative study platform for university students with real-time document editing, flashcard generation, and session scheduling.',
      techStack: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Socket.io'],
      skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'REST APIs'],
      impactStatement: 'Used by 400+ students at UC Berkeley; reduced study group coordination time by 60%.',
      url: 'https://studysync.alexchen.dev',
      startDate: '2023-09-01',
      endDate: '2024-01-15',
    },
    {
      id: 'proj-2',
      name: 'PriceWatch API',
      description: 'A REST API service that aggregates product prices from multiple e-commerce sources and sends alerts on price drops.',
      techStack: ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker'],
      skills: ['Python', 'FastAPI', 'REST APIs', 'PostgreSQL', 'Docker'],
      impactStatement: 'Handles 10k daily requests with sub-200ms p95 latency. Deployed on AWS EC2.',
      url: 'https://github.com/alexchen-dev/pricewatch-api',
      startDate: '2023-03-01',
      endDate: '2023-07-01',
    },
    {
      id: 'proj-3',
      name: 'ML Course Grade Predictor',
      description: 'Trained a gradient boosting model on historical course data to predict student final grades with 83% accuracy.',
      techStack: ['Python', 'scikit-learn', 'pandas', 'Jupyter'],
      skills: ['Python', 'Machine Learning', 'Data Analysis'],
      impactStatement: 'Presented at departmental research showcase; model integrated into faculty advising tool.',
      startDate: '2023-01-01',
      endDate: '2023-05-01',
    },
  ],
  experiences: [
    {
      id: 'exp-1',
      company: 'Stripe',
      role: 'Software Engineering Intern',
      description: 'Worked on the Payments Infrastructure team, building internal tooling to automate reconciliation workflows.',
      skills: ['Python', 'PostgreSQL', 'REST APIs', 'Git'],
      startDate: '2024-06-01',
      endDate: '2024-08-31',
      current: false,
      bullets: [
        'Built an internal dashboard (Python + React) for reconciliation anomaly detection, reducing manual review time by 40%.',
        'Wrote 3 new REST API endpoints consumed by the billing team, documented with OpenAPI.',
        'Participated in on-call rotation for 2 weeks; resolved 2 production incidents under supervision.',
      ],
    },
    {
      id: 'exp-2',
      company: 'UC Berkeley EECS Dept.',
      role: 'Teaching Assistant — CS 61B Data Structures',
      description: 'Held weekly office hours for 30+ students, graded projects, and developed new autograder test cases.',
      skills: ['Java', 'Git', 'Communication'],
      startDate: '2023-08-01',
      endDate: '2024-05-31',
      current: false,
      bullets: [
        'Held weekly office hours serving 30+ students on data structures and algorithms concepts.',
        'Developed 15 new autograder test cases for the graph traversal project.',
        'Received 4.7/5.0 average student satisfaction rating.',
      ],
    },
  ],
  education: [
    {
      id: 'edu-1',
      institution: 'University of California, Berkeley',
      degree: 'B.S.',
      field: 'Electrical Engineering and Computer Sciences',
      startDate: '2022-08',
      endDate: '2026-05',
      current: true,
      gpa: '3.8',
      location: 'Berkeley, CA',
    },
  ],
  certifications: [
    {
      id: 'cert-1',
      name: 'AWS Certified Cloud Practitioner',
      issuer: 'Amazon Web Services',
      dateObtained: '2023-11-01',
      url: 'https://aws.amazon.com/certification/',
    },
  ],
  roleInterests: [
    {
      id: 'ri-1',
      title: 'Backend Engineer',
      seniority: 'entry',
      domains: ['FinTech', 'SaaS', 'Developer Tools'],
      remote: true,
      locations: ['San Francisco, CA', 'New York, NY', 'Remote'],
    },
    {
      id: 'ri-2',
      title: 'Full Stack Engineer',
      seniority: 'entry',
      domains: ['SaaS', 'EdTech'],
      remote: true,
      locations: ['San Francisco, CA', 'Remote'],
    },
  ],
  updatedAt: '2026-02-20T10:00:00Z',
};
